// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnAjIY4-MyGW8-tDdawUOWiFGvMvsKWSQ',
    appId: '1:270104643692:web:21471cf665e0549175f049',
    messagingSenderId: '270104643692',
    projectId: 'e-ports-d00e1',
    authDomain: 'e-ports-d00e1.firebaseapp.com',
    storageBucket: 'e-ports-d00e1.firebasestorage.app',
    measurementId: 'G-9Z8LSPKGE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdmhJG4DPrbTL6DIusva6RCtOnDsxWTRM',
    appId: '1:270104643692:android:41b2c58a9f95b5a675f049',
    messagingSenderId: '270104643692',
    projectId: 'e-ports-d00e1',
    storageBucket: 'e-ports-d00e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiYXROItjaC7GdQ1qyNAjV9QG2UR0DtOM',
    appId: '1:270104643692:ios:d9593440b4a70ce075f049',
    messagingSenderId: '270104643692',
    projectId: 'e-ports-d00e1',
    storageBucket: 'e-ports-d00e1.firebasestorage.app',
    iosBundleId: 'com.example.eSports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiYXROItjaC7GdQ1qyNAjV9QG2UR0DtOM',
    appId: '1:270104643692:ios:d9593440b4a70ce075f049',
    messagingSenderId: '270104643692',
    projectId: 'e-ports-d00e1',
    storageBucket: 'e-ports-d00e1.firebasestorage.app',
    iosBundleId: 'com.example.eSports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnAjIY4-MyGW8-tDdawUOWiFGvMvsKWSQ',
    appId: '1:270104643692:web:4324ecc83166ca8775f049',
    messagingSenderId: '270104643692',
    projectId: 'e-ports-d00e1',
    authDomain: 'e-ports-d00e1.firebaseapp.com',
    storageBucket: 'e-ports-d00e1.firebasestorage.app',
    measurementId: 'G-ZJBPG5S2VF',
  );
}
